CREATE TABLE MEMO (
    ID      INT PRIMARY KEY,
    CONTENT VARCHAR(200) NOT NULL
);

INSERT INTO MEMO VALUES (1, '첫번째 메모');
INSERT INTO MEMO VALUES (2, '두번째 메모');
INSERT INTO MEMO VALUES (3, '세번째 메모');